(define (make-table)
  (let ((local-table (list '*table*)))
    (define (lookup key-1 key-2)
      (let ((subtable (assoc key-1 (cdr local-table))))
        (if subtable
            (let ((record (assoc key-2 (cdr subtable))))
              (if record
                  (cdr record)
                  false))
            false)))
    (define (insert! key-1 key-2 value)
      (let ((subtable (assoc key-1 (cdr local-table))))
        (if subtable
            (let ((record (assoc key-2 (cdr subtable))))
              (if record
                  (set-cdr! record value)
                  (set-cdr! subtable
                            (cons (cons key-2 value)
                                  (cdr subtable)))))
            (set-cdr! local-table
                      (cons (list key-1
                                  (cons key-2 value))
                            (cdr local-table)))))
      'ok)    
    (define (dispatch m)
      (cond ((eq? m 'lookup-proc) lookup)
            ((eq? m 'insert-proc!) insert!)
            (else (error "Unknown operation - TABLE" m))))
    dispatch))
(define operation-table (make-table))
(define get (operation-table 'lookup-proc))
(define put (operation-table 'insert-proc!))

(define (attach-tag type-tag contents)
  (cons type-tag contents)) ;;may be list
(define (type-tag datum)
  (if (pair? datum) (car datum)
      (error "bad datum")))
(define (contents datum)
  (if (pair? datum) (cdr datum)
      (error "bad datum")))

(define (install-scheme-number-package)
  (define (tag x)(attach-tag 'scheme-number x))
  (put 'sum '(scheme-number scheme-number)
       (lambda (x y)(tag (+ x y))))
  (put 'sub '(scheme-number scheme-number)
       (lambda (x y)(tag (- x y))))
  (put 'product '(scheme-number scheme-number)
       (lambda (x y)(tag (* x y))))
  (put 'div '(scheme-number scheme-number)
       (lambda (x y)(tag (/ x y))))
  (put 'make 'scheme-number
       (lambda (x) (tag x))))
(install-scheme-number-package)
(define (make-scheme-number n)
  ((get 'make 'scheme-number) n))

(define (install-rational-package)
  ;;internal precedures
  (define (numer x)(car x))
  (define (denom x)(cdr x))
  (define (make-rat n d)(cons n d))
  (define (add-rat a b)(make-rat (+ (* numer(a) denom(b)) (* numer(b) denom(a))) (* denom(a) denom(b))))
  (define (sub-rat a b)(make-rat (- (* numer(a) denom(b)) (* numer(b) denom(a))) (* denom(a) denom(b))))
  (define (mul-rat a b)(make-rat (* numer(a) numer(b)) (* denom(a) denom(b))))
  (define (div-rat a b)(make-rat (* numer(a) denom(b)) (* denom(a) numer(b))))
  ;;interface to system
  (define (tag x)(attach-tag 'rational x))
  (put 'sum '(rational rational)
       (lambda(x y)(tag (add-rat x y))))
  (put 'sub '(rational rational)
       (lambda(x y)(tag (sub-rat x y))))
  (put 'product '(rational rational)
       (lambda(x y)(tag (mul-rat x y))))
  (put 'div '(rational rational)
       (lambda(x y)(tag (div-rat x y))))
  (put 'make 'rational (lambda (n d)(tag (make-rat n d)))))
(install-rational-package)
(define (make-rational n d)
  ((get 'make 'rational) n d))

(define (apply-generic op . args)
  (let ((type-tags (map type-tag args)))
    (let ((proc (get op type-tags)))
      (if proc (apply proc (map contents args))
          (error "no avialable")))))

(define (addition a b)(apply-generic 'sum a b))
(define (substraction a b)(apply-generic 'sub a b))
(define (multiplication a b)(apply-generic 'product a b))
(define (division a b)(apply-generic 'div a b))

(define x (make-rational 1 2))
(define y (make-rational 2 4))
(newline)
(newline)
(display (multiplication x y))
(newline)
(newline)
(newline)

